### ISSUE TITLE
无法使用

### ISSUE THREAD

**Issue by leo369258** [mac-zhou/homeassistant-mi-acpartner#14]
你好，在HA 0.62.1版本下无法使用，程序报错，报错信息如下：

[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.setup] Setup of domain climate took 6.0 seconds.[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=turn_on>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=turn_off>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_swing_mode>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_operation_mode>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_fan_mode>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_humidity>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_temperature>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_aux_heat>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_hold_mode>[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.core] Bus:Handling <Event service_registered[L]: domain=climate, service=set_away_mode>[0m
TypeError: build() takes 2 positional arguments but 3 were given[0m
m = Message.build(msg, ctx)
File "/usr/local/lib/python3.6/site-packages/miio/device.py", line 216, in send
getstate = self.climate.send("get_model_and_state", [])
File "/config/custom_components/climate/mi_acpartner.py", line 485, in climate_get_state
self._state = self.climate_get_state()
File "/config/custom_components/climate/mi_acpartner.py", line 214, in __init__
token, sensor_entity_id, sync, customize),
File "/config/custom_components/climate/mi_acpartner.py", line 141, in setup_platform
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
raise self._exception
File "/usr/local/lib/python3.6/asyncio/futures.py", line 243, in result
return fut.result()
File "/usr/local/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
SLOW_SETUP_MAX_WAIT, loop=self.hass.loop)
File "/usr/src/app/homeassistant/helpers/entity_component.py", line 189, in _async_setup_platform
Traceback (most recent call last):
[31m2019-06-25 09:35:46 ERROR (MainThread) [homeassistant.components.climate] Error while setting up platform mi_acpartner[0m
[32m2019-06-25 09:35:46 INFO (SyncWorker_11) [custom_components.climate.mi_acpartner] initializing with host 192.168.50.84 token 2dfffe58ab82a163650586f255f1dbda[0m
[32m2019-06-25 09:35:46 INFO (MainThread) [homeassistant.components.climate] Setting up climate.mi_acpartner[0m

**Comment by 0xbw** [comment]
takes 2 positional arguments but 3 were given

你可能配置有些问题，请贴出配置

我已很久未更新，建议使用 https://github.com/syssi/xiaomi_airconditioningcompanion

**Comment by leo369258** [comment]
climate:
  - platform: mi_acpartner
    name: mi_acpartner
    host: 192.168.50.84
    token: 2dfffe58ab82a163650586f255f1dbda
    target_sensor: sensor.temperature_158d00015aefc4

**Comment by 0xbw** [comment]
看着我的代码看不支持miio新版本了 请移步 https://github.com/syssi/xiaomi_airconditioningcompanion
