### ISSUE TITLE
home-assistant 59.2 疑似失效

### ISSUE THREAD

**Issue by killadm** [mac-zhou/homeassistant-mi-acpartner#6]
启动报错
`2017-12-14 22:09:48 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step
    result = coro.send(None)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 399, in async_process_entity
    new_entity, self, update_before_add=update_before_add
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 247, in async_add_entity
    yield from entity.async_update_ha_state()
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
    attr)
  File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 333, in _attr_setter
    value = getattr(self, name)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 736, in supported_features
    raise NotImplementedError()
NotImplementedError`

[https://community.home-assistant.io/t/honeywell-lyric-thermostat/3520/303](url)提到

> All climate platforms are required to implement the supported_features method now. Custom components must adapt to this. Sorry for breaking this, but with changes like this, we can only adapt the “official” platform ourselves.

貌似climate 现在强制要求实现 supported_features 方法

**Comment by 0xbw** [comment]
感谢提出问题，我最近看看

mac_zhou

在 2017年12月14日，22:39，killadm <notifications@github.com<mailto:notifications@github.com>> 写道：


启动报错
2017-12-14 22:09:48 ERROR (MainThread) [homeassistant.core] Error doing job: Task exception was never retrieved Traceback (most recent call last): File "/usr/lib/python3.6/asyncio/tasks.py", line 179, in _step result = coro.send(None) File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 399, in async_process_entity new_entity, self, update_before_add=update_before_add File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity_component.py", line 247, in async_add_entity yield from entity.async_update_ha_state() File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 231, in async_update_ha_state attr) File "/usr/lib/python3.6/site-packages/homeassistant/helpers/entity.py", line 333, in _attr_setter value = getattr(self, name) File "/usr/lib/python3.6/site-packages/homeassistant/components/climate/__init__.py", line 736, in supported_features raise NotImplementedError() NotImplementedError

https://community.home-assistant.io/t/honeywell-lyric-thermostat/3520/303<url>提到

All climate platforms are required to implement the supported_features method now. Custom components must adapt to this. Sorry for breaking this, but with changes like this, we can only adapt the “official” platform ourselves.

貌似climate 现在强制要求实现 supported_features 方法

**Comment by 0xbw** [comment]
已经支持HA 0.59.2 请更新
