### ISSUE TITLE
重写插件

### ISSUE THREAD

**Issue by cxlwill** [mac-zhou/homeassistant-mi-acpartner#7]
官方 Climate 组件似乎更新，另外 miio 亦加入了空调伴侣的内容。我们是不是要考虑重写这货了

**Comment by 0xbw** [comment]
我就是等着miio更新，然后重写
但miio还没发release 吧

mac_zhou

在 2017年12月14日，23:28，cxlwill <notifications@github.com<mailto:notifications@github.com>> 写道：


官方 Climate 组件似乎更新，另外 miio 亦加入了空调伴侣的内容。我们是不是要考虑重写这货了

**Comment by cxlwill** [comment]
加了一个雏形，不过确实是 pre-release，但是我们不能光靠 miio，因为 syssi 他们应该是没有这个设备的。所以估计要靠我们这里提供信息。

**Comment by 0xbw** [comment]
嗯，我今天来重写一下试试

**Comment by cxlwill** [comment]
更新HA 至 0.60.0，miio 至 0.3.3，手动修改 import 版本后出现以下 ERROR：
```
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 231, in async_update_ha_state
    attr)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/helpers/entity.py", line 333, in _attr_setter
    value = getattr(self, name)
  File "/srv/homeassistant/homeassistant_venv/lib/python3.5/site-packages/homeassistant/components/climate/__init__.py", line 736, in supported_features
    raise NotImplementedError()
NotImplementedError`
```
